name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '>=20.6.0'
      - run: npm install
      - run: npm test

#      - run: npm run build
#
#      - name: Get REV
#        id: rev
#        run: echo "REV=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: 'Stylus-test-${{ steps.rev.outputs.REV }}'
#          path: 'dist/*'
#          if-no-files-found: error
